colors:
  red:
    low_1: [0,140,100]
    high_1: [15,255,255]
    low_2: [165,140,100]
    high_2: [180,255,255]
  white:
    low:  [0,0,150]
    high:  [180,60,255]
  yellow:
    low: [25,140,100]
    high: [45,255,255]

canny_thresholds: [80,200]
canny_aperture_size: 3
dilation_kernel_size: 3
hough_threshold: 2
hough_min_line_length: 3
hough_max_line_gap: 1