version: 2.1
workflows:
  version: 2
  build:
      jobs:
        - build-docs
        - unit-tests
jobs:
  build-docs:
    docker:
      - image: ubuntu:18.04

    steps:
      - setup_remote_docker

      - run:
          name: Install dependencies
          command: |
            apt update && \
            apt install -y python3-pip git git-lfs curl && \
            rm -rf /var/lib/apt/lists/*

      - run:
          name: Install Docker
          command: |
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
            rm get-docker.sh

      - run:
          name: Install dts
          command: |
            python3 -m pip install --no-cache-dir --user -U duckietown-shell
            export PATH="$PATH:$HOME/.local/bin"
            dts --set-version daffy exit

      - checkout

      - run:
          name: Build the docs
          command: |
            export PATH="$PATH:$HOME/.local/bin"
            dts devel build --docs

      - run:
          name: run tests
          command:
            make test-circle

      - store_artifacts:
          path: html/out
          destination: html

      - store_artifacts:
          path: html/out/package.tgz
          destination: out/package.tgz
  unit-tests:
    docker:
      - image: ubuntu:18.04

    steps:
      - setup_remote_docker

      - run:
          name: Install dependencies
          command: |
            apt update && \
            apt install -y python3-pip git git-lfs curl && \
            rm -rf /var/lib/apt/lists/*

      - run:
          name: Install Docker
          command: |
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
            rm get-docker.sh

      - run:
          name: Install dts
          command: |
            python3 -m pip install --no-cache-dir --user -U duckietown-shell
            export PATH="$PATH:$HOME/.local/bin"
            dts --set-version daffy exit

      - checkout

      - run:
          name: Build the docs
          command: |
            export PATH="$PATH:$HOME/.local/bin"
            dts devel build --docs

      - run:
          name: run tests
          command:
            make test-circle

      - store_artifacts:
          path: html/out
          destination: html

      - store_artifacts:
          path: html/out/package.tgz
          destination: out/package.tgz
