version: "2.1"
workflows:
  version: "2"
  all_of_them:
    jobs:
      - build-docs
      - unit-tests-from-parent
jobs:
  build-docs:
    docker:
      - image: ubuntu:18.04

    steps:
      - setup_remote_docker

      - run:
          name: Install dependencies
          command: |
            apt update && \
            apt install -y python3-pip git git-lfs curl && \
            rm -rf /var/lib/apt/lists/*

      - run:
          name: Install Docker
          command: |
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
            rm get-docker.sh

      - run:
          name: Install dts
          command: |
            python3 -m pip install --no-cache-dir --user -U duckietown-shell
            export PATH="$PATH:$HOME/.local/bin"
            dts --set-version daffy exit

      - checkout

      - run:
          name: Build the docs
          command: |
            export PATH="$PATH:$HOME/.local/bin"
            dts devel build --docs


      - store_artifacts:
          path: html/out
          destination: html

      - store_artifacts:
          path: html/out/package.tgz
          destination: out/package.tgz

  unit-tests-from-parent:
    docker:
      - image:  duckietown/dt-ros-commons:daffy-amd64
    environment:
      DUCKIETOWN_DATA: /data
    steps:

      - checkout
      - run:
          name: Install dts
          command: |
            python3 -m pip install --no-cache-dir --user -U duckietown-shell
            export PATH="$PATH:$HOME/.local/bin"
            dts --set-version daffy exit
      - run:
          name: Install dts
          command: |
            python3 -m pip install --no-cache-dir --user -U duckietown-shell
            export PATH="$PATH:$HOME/.local/bin"
            dts --set-version daffy exit
      - run:
          name: deps
          command: |
            pip3 install --use-feature=2020-resolver -r dependencies-py3.txt
      - run:
          name: apt
          command: |
            dt-apt-install dependencies-apt.txt
      - run:
          name: deps
          command: |
            ls -la /code/catkin_ws/src
            ln -s  `pwd` /code/catkin_ws/src/dt-core
            ls -la /code/catkin_ws/src
            . /opt/ros/noetic/setup.sh && catkin build --workspace ${CATKIN_WS_DIR}/
            pip3 install duckietown-utils-daffy
      - run:
          name: run tests
          command:
            . /opt/ros/noetic/setup.sh && . /code/catkin_ws/devel/local_setup.bash && make test-circle


