description: Localizing on a curve left 
constructor: lane_filter_generic.LaneFilterGeneric
parameters: 
  configuration:
      delta_d: 0.0024
      delta_phi: 0.022
      d_max: 0.3025 # add half
      d_min: -0.15 
      phi_min: -1.5
      phi_max: 1.5125

      localization_template: DT17_template_before_curve_left
      min_max: 0.1
      
      delta_segment: 0.05