description: Four way intersection (seen by a straight tile)
constructor: duckietown_segmaps.compose_maps
parameters: 
    grid_spacing: 0.584
    tiles:
    - cell: [0, 0]
      name: DT17_straight_stop_tile
      rotation: 0
    - cell: [1, 0]
      name: DT17_empty_tile
      rotation: 0
    - cell: [1, 1]
      name: DT17_straight_stop_tile
      rotation: -90
#     - cell: [1, 2]
#       name: DT17_straight_tile
#       rotation: -90
    - cell: [1, -1]
      name: DT17_straight_stop_tile
      rotation: 90
#     - cell: [1, -2]
#       name: DT17_straight_tile
#       rotation: 90
    - cell: [2, 0]
      name: DT17_straight_stop_tile
      rotation: -180
    - cell: [3, 0]
      name: DT17_straight_tile
      rotation: -180
