description: Curve right
constructor: duckietown_segmaps.get_map_curve 
parameters: 
    tile_size: 0.558 # outer white to outer white
    tile_spacing: 0.584 
    width_yellow: 0.024 
    width_white: 0.048 
    gap_len: 0.015
    dash_len: 0.04
    direction: right