description: Three way intersection (seen by the middle)
constructor: duckietown_segmaps.compose_maps
parameters: 
    grid_spacing: 0.584
    tiles:
    - cell: [0, 0]
      name: DT17_straight_stop_tile
      rotation: 0
    - cell: [1, 0]
      name: DT17_three_way_center
      rotation: 0
    - cell: [1, 1]
      name: DT17_straight_stop_tile
      rotation: -90
    - cell: [1, 2]
      name: DT17_straight_tile
      rotation: -90
    - cell: [1, -1]
      name: DT17_straight_stop_tile
      rotation: 90
    - cell: [1, -2]
      name: DT17_straight_tile
      rotation: 90

