description: Before a curve right (straight, right, straight)
constructor: duckietown_segmaps.compose_maps
parameters: 
    grid_spacing: 0.584
    tiles:
    - cell: [0, 0]
      name: DT17_straight_tile
      rotation: 0
    - cell: [1, 0]
      name: DT17_curve_right
      rotation: 0
    - cell: [1, -1]
      name: DT17_straight_tile
      rotation: -90
